### ISSUE TITLE
There is no beacon.stub in templates

### ISSUE THREAD

**Issue by FlusherDock1** [rainlab/deploy-plugin#1]
Fresh install, fresh plugin, just created server inside it

Can't download beacon archive. 

file_get_contents(D:\laragon\www\october\plugins/rainlab/deploy/beacon/templates/app/bootstrap/beacon.stub): failed to open stream: No such file or directory
~\plugins\rainlab\deploy\classes\ArchiveBuilder.php line 22

gist: https://gist.github.com/FlusherDock1/2d9a18724e25cd41df62f74a1476a2c8

**Comment by LeMaX10** [comment]
@daftspunk Isn't it more expedient to get this data directly from the project repository instead of stubs in the plugin?

**Comment by daftspunk** [comment]
@FlusherDock1 Thanks for trying to test it! This is still under development, hopefully should have a proof of concept ready in the coming days. This particular file has a large security bounty on it so it hasn't been published yet.

@LeMaX10 These stub files are modified slightly and are based on concrete bootstrappers that have not changed in the entire history of the project, and will be unlikely to ever change. Where project files are needed they are taken from the local copy of October CMS instead. The idea is to decouple the workflow from October CMS' server and repo as a dependency. It operates completely standalone. This is an intentional design decision so there are zero dependencies on October CMS.

**Comment by daftspunk** [comment]
Removed the bounty message and added the script in c84565cd5e68bbf93374faa0de9cc1cd179d0a3e

Happy testing
