### ISSUE TITLE
Public Folder

### ISSUE THREAD

**Issue by hackolein** [rainlab/deploy-plugin#13]
Hi,

is it possible to us that deployment plugin, if I use an public folder (october:mirror)?

**Comment by daftspunk** [comment]
Hello,

Yes, this plugin will work great with the public folder, since the `october:mirror` command will create symlinks that are 1:1 links to deployed files.

However, the deployment plugin won't have the necessary privileges to perform the mirror command itself. So when deploying a new theme or plugin, you must perform the mirror command manually.

I hope this helps!
