### ISSUE TITLE
Move payload to body contents - Error 414: URI is too long

### ISSUE THREAD

**Issue by Exodon** [rainlab/deploy-plugin#28]
Hi

I was trying to use this deploy plugin but got this error :

**Update Failed**
_A valid response from a beacon was not found. Add ?debug=1 to your URL, try again and check the logs (Code: 414)_

Steps to reproduce : 

1. Setup plugin and generate the files and upload to production server
2. Test the beacon connection (was positive)
3. Click **install october cms**
4. Choose mysql and add the correct database and user name;
5. Click install october cms

After all this steps gave me this error : 

**Update Failed**
_A valid response from a beacon was not found. Add ?debug=1 to your URL, try again and check the logs (Code: 414)
![deploy](https://user-images.githubusercontent.com/3321409/141705223-8101d907-69fd-4e0a-afb0-e2b3f25f33f6.gif)
_

thanks in advanced

**Comment by daftspunk** [comment]
Hi @Exodon 

The error 414 suggests that the URL is too long and was not accepted by the server. This is because the payload is contained entirely within the URL. We will look at fixing this in a later release.

In the meantime, you may need to see if you can increase this limitation in your web server configuration.

**Comment by daftspunk** [comment]
This is fixed in v1.1.0
