### ISSUE TITLE
Update Failed - 500 Internal Server Error

### ISSUE THREAD

**Issue by mlieshout** [rainlab/deploy-plugin#41]
Hi,

Is there any way to debug a "500 Internal Server Error" error? It shows right after "Deploying Core Archive".
There is an arc file in storage/temp: ocb-xxxxx.arc

When I unzip the arc file, the files have the wrong file permissions:
- files: 666
- directories: 777

I guess that causes the 500 error.

**Comment by daftspunk** [comment]
Hello,

Setting the default permission masks, on the server, to something more relaxed might help:

```
DEFAULT_FILE_MASK=775
DEFAULT_FOLDER_MASK=775
```

**Comment by mlieshout** [comment]
Hi,

Thanks, but that doesn't work. 

I've tried another server and repeated the deployment several times. Sometimes it works; sometimes it gives a 500 error during "Deploying Core Archive". 

I've turned off mod_security, raised max_execution_time and max_input_time. I checked the logs, but nothing is logged regarding this error. Is there anything else I can do to get more insight into the local deployment process?

**Comment by daftspunk** [comment]
In the backend URL, before deployment add `?debug=1` to see if the server responds with any meaningful message -- the message will be in the October CMS logs (storage/logs/system.log).

Otherwise, an error 500 should store something in the web server logs that you can check.

The exact error message would be useful to find the problem. The webserver should be able to read its own files that it created.

**Comment by mlieshout** [comment]
At exactly 30 seconds, I get an error 500. It happens during the post request: "Deploying+Core+Archive".
There is nothing in the logs, just an error in the browser console: "500 Internal Server Error".

I've added the following Nginx directives:
proxy_connect_timeout 900s;
proxy_send_timeout 900s;
proxy_read_timeout 900s;
fastcgi_send_timeout 900s;
fastcgi_read_timeout 900s;
send_timeout 900s;

PHP-settings are:
max_execution_time = 600
max_input_time = 600

It doesn't fix the problem. 

<img width="921" alt="Screenshot 2022-07-02 at 10 36 10" src="https://user-images.githubusercontent.com/994055/176995169-11ecdbba-5540-48e3-ac17-a1564c7d6ed5.png">

**Comment by daftspunk** [comment]
Halting at exactly 30 seconds is a good observation because it shows that the server may not be accepting the adjusted configuration. Some things to try:

- First: Double check the setting on your local environment. It's possible that the local web server is applying a 30-second timeout limit. Both local and remote servers will require a longer execution time.

- Second: It's also possible that the hosting does not allow this value to be modified, effectively ignoring any attempts to change it via the PHP settings. Contact your hosting provider to see if this is the case. Show them that you've modified the setting to 600 seconds and the script halts at precisely 30 seconds (not the expected 600).

**Comment by mlieshout** [comment]
Checking the local environment did the trick: I switched from MAMP to Laravel Valet and the problem was solved.

I focused too much on the destination server, I totally forgot that the local webserver could also be causing this issue.

Thanks!
