### ISSUE TITLE
May add fetch and deploy database and storage as feature 

### ISSUE THREAD

**Issue by renickbuettner** [rainlab/deploy-plugin#7]
In my use case it would be very handy, to also fetch and deploy the remote storage media folder, and the remote database. Especially when working with smaller sites and sqlite, it's handy to work with real website content. 

With this feature I imagine a workflow similar like this:

- fetch data with user changes from remote
- add fancy shiny new widgets and buttons
- deploy to test server, and receive feedback
- deploy to production

(sorry I lied, there's no deployment to test server 🤣)

---

This was just an idea I had for this plugin. Feel free to just delete this ticket if you don't see this as a valid use case.

**Comment by daftspunk** [comment]
Hey @renickbuettner 

Thanks for your insights! This falls under backup capture restoration. We have plans to include this as part of the platform. It's a great idea and we could get the deploy plugin to automate it. 

We will close this since it is already under consideration. 

As another idea, this plugin is quite extensible so you could implement more direct functionality as another plugin.
